#include <stdio.h>

#define EXTREMELY_DESCRIPTIVE_CONSTANT_THAT_DOUBLES_VALUES 2
#define TOTAL_NUMBER_OF_ELEMENTS_IN_SOURCE_VARIABLE_ARRAY 5
#define SIZE_OF_DESTINATION_VARIABLE_ARRAY_WHICH_RECEIVES_DOUBLED_VALUES 5
#define SIZE_OF_THE_DESTINATION_ARRAY_USED_FOR_ASSEMBLY_STYLE_LOGIC 5
#define THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE i

int main()
{
    int src[TOTAL_NUMBER_OF_ELEMENTS_IN_SOURCE_VARIABLE_ARRAY] = { 1, 3, 5, 7, 9 };
    int dest[SIZE_OF_DESTINATION_VARIABLE_ARRAY_WHICH_RECEIVES_DOUBLED_VALUES] = { 0 };
    int destasm[SIZE_OF_THE_DESTINATION_ARRAY_USED_FOR_ASSEMBLY_STYLE_LOGIC] = { 0 };

    for (int THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE = 0; THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE < TOTAL_NUMBER_OF_ELEMENTS_IN_SOURCE_VARIABLE_ARRAY; THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE++)
    {
        dest[THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE] = src[THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE] * EXTREMELY_DESCRIPTIVE_CONSTANT_THAT_DOUBLES_VALUES;
    }

    __asm {
        lea esi, src;
        lea edi, destasm;
        mov ecx, 5;

        loop_start :
        lodsd;
            add eax, eax;
            mov[edi], eax;
            add edi, 4;
            loop loop_start;
    }



    for (int THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE = 0; THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE < TOTAL_NUMBER_OF_ELEMENTS_IN_SOURCE_VARIABLE_ARRAY; THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE++)
    {
        printf("src[%d] = %d, ", THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE, src[THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE]);

        printf("dest[%d] = %d, ", THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE, dest[THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE]);

        printf("destasm[%d] = %d\n", THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE, destasm[THE_LEGENDARY_AND_WELL_RESPECTED_SINGLE_ITERATOR_VARIABLE]);
    }



    return 0;
}
